# Setup

In [1]:
import numpy as np
import tensorflow as tf
import tf_encrypted as tfe

2022-11-01 10:11:41.161351: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-01 10:11:41.165199: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-01 10:11:41.165212: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-11-01 10:11:42.411596: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-11-01 10:11:42.411624: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to c

# Protocol

We have to use the same configuration as used by the server, including player configuration and protocol.

In [2]:
config = tfe.RemoteConfig.load("./tfe.config")
config.connect_servers()
tfe.set_config(config)
tfe.set_protocol(tfe.protocol.Pond())

2022-11-01 10:11:42.478839: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job tfe -> {0 -> localhost:4000, 1 -> localhost:4001, 2 -> localhost:4002}
2022-11-01 10:11:42.478874: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:47107}
2022-11-01 10:11:42.486277: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job tfe -> {0 -> localhost:4000, 1 -> localhost:4001, 2 -> localhost:4002}
2022-11-01 10:11:42.486297: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:47107}
2022-11-01 10:11:42.486804: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:438] Started server with target: grpc://localhost:47107


# Running

To run computations on the servers we create a new `tfe.serving.QueueClient`.

Note that we currently have to provide the input and output shapes for the computation (but not the computation itself)

In [3]:
input_shape = (5, 5)
output_shape = (5, 5)

In [4]:
client = tfe.serving.QueueClient(
    input_shape=input_shape,
    output_shape=output_shape)

In [5]:
res = client.run(np.full(input_shape, 5))
print(res)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(
[[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]], shape=(5, 5), dtype=float64)
