# Setup

In [1]:
import numpy as np
import tensorflow as tf
import tf_encrypted as tfe

In [2]:
%load_ext tensorboard.notebook

TENSORBOARD_DIR = "/tmp/tensorboard"

tfe.set_tfe_trace_flag(True)
tfe.set_tfe_events_flag(True)
tfe.set_log_directory(TENSORBOARD_DIR)

INFO:tf_encrypted:Writing trace files
INFO:tf_encrypted:Writing event files for each run with a tag
INFO:tf_encrypted:Writing event and trace files to '/tmp/tensorboard'


# Protocol

We have to use the same configuration as used by the server, including player configuration and protocol.

In [3]:
config = tfe.RemoteConfig.load("/tmp/tfe.config")

tfe.set_config(config)
tfe.set_protocol(tfe.protocol.Pond())

# Running

To run computations on the servers we create a new `tfe.serving.QueueClient`.

Note that we currently have to provide the input and output shapes for the computation (but not the computation itself)

In [4]:
input_shape = (5, 5)
output_shape = (5, 5)

In [5]:
client = tfe.serving.QueueClient(
    input_shape=input_shape,
    output_shape=output_shape)

In [6]:
sess = tfe.Session(config=config)

INFO:tf_encrypted:Starting session on target 'grpc://localhost:4000' using config graph_options {
}



In [7]:
res = client.run(
    sess,
    np.full(input_shape, 5))

print(res)

[[25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]]
